# Generated by Django 6.0.7 on 2026-07-31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=200)),
                ("normalized_name", models.CharField(db_index=True, editable=False, max_length=200)),
                ("gender", models.CharField(choices=[("Man", "Man"), ("Woman", "Woman")], max_length=5)),
                ("country_calling_code", models.CharField(default="+98", max_length=5)),
                ("phone_number", models.CharField(max_length=14)),
                ("phone_e164", models.CharField(db_index=True, max_length=16)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("patient_note", models.TextField(blank=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ("clinic", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="patients", to="accounts.clinic")),
            ],
            options={
                "ordering": ["normalized_name", "id"],
                "indexes": [
                    models.Index(fields=["clinic", "normalized_name"], name="patient_clinic_name_idx"),
                    models.Index(fields=["clinic", "phone_e164"], name="patient_clinic_phone_idx"),
                ],
            },
        ),
    ]
