# Generated by Django 6.0.7 on 2026-07-31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("appointment", "Appointment"),
                            ("walk_in", "Walk-in"),
                        ],
                        max_length=16,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("scheduled_time", models.TimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("patient_full_name_snapshot", models.CharField(editable=False, max_length=200)),
                ("patient_gender_snapshot", models.CharField(editable=False, max_length=5)),
                ("patient_phone_snapshot", models.CharField(editable=False, max_length=16)),
                (
                    "patient_date_of_birth_snapshot",
                    models.DateField(blank=True, editable=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="accounts.clinic",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "scheduled_time", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["clinic", "date"],
                        name="visit_clinic_date_idx",
                    ),
                    models.Index(
                        fields=["clinic", "patient", "date"],
                        name="visit_patient_date_idx",
                    ),
                ],
            },
        ),
    ]
