from django.urls import path

from .views import (
    AssistantRecoveryInitiateView, AssistantSetupClaimView, AssistantSetupInfoView, AssistantSetupView,
    ClaimDoctorMembershipView, ClinicAssistantView, ClinicContextView, ClinicCreateView,
    DeviceContactAuthorizationConfirmView, DeviceContactAuthorizationRequestView,
    DevicePairingApproveView, DevicePairingStartView, DevicePairingStatusView,
    EmailChangeConfirmView, EmailChangeRequestView, HealthView,
    InitialEmailVerificationConfirmView, InitialEmailVerificationRequestView,
    InitialPhoneVerificationConfirmView, InitialPhoneVerificationRequestView, LeaveClinicView,
    PasskeyAuthenticationCompleteView, PasskeyAuthenticationOptionsView, PasskeyDeleteView, PasskeyListView,
    PasskeyReauthenticationCompleteView, PasskeyRegistrationCompleteView, PasskeyRegistrationOptionsView,
    PasswordChangeConfirmView, PasswordChangeRequestView, PhoneChangeConfirmView, PhoneChangeRequestView,
    ReauthenticatePasswordView, RecoveryCodeConfirmView, RecoveryCodeListView, RecoveryConfirmView,
    RecoveryRequestView, RecoveryResetView, SelectClinicView, StaffAccountDeleteView, StaffLoginView,
    StaffLogoutView, StaffMeView, StaffPrivateNoteView, StaffProfileView, StaffRegisterView, VerificationContactUpdateView,
    TrustedDeviceDeleteView, TrustedDeviceListView,
)

urlpatterns = [
    path("health/", HealthView.as_view()),
    path("clinics/", ClinicCreateView.as_view()),
    path("clinic/context/", ClinicContextView.as_view()),
    path("clinics/<uuid:clinic_id>/claim-doctor/", ClaimDoctorMembershipView.as_view()),
    path("staff/register/", StaffRegisterView.as_view()),
    path("staff/login/", StaffLoginView.as_view()),
    path("staff/me/", StaffMeView.as_view()),
    path("staff/profile/", StaffProfileView.as_view()),
    path("staff/account/", StaffAccountDeleteView.as_view()),
    path("staff/select-clinic/", SelectClinicView.as_view()),
    path("staff/leave-clinic/", LeaveClinicView.as_view()),
    path("staff/verify/email/request/", InitialEmailVerificationRequestView.as_view()),
    path("staff/verify/email/confirm/", InitialEmailVerificationConfirmView.as_view()),
    path("staff/verify/phone/request/", InitialPhoneVerificationRequestView.as_view()),
    path("staff/verify/phone/confirm/", InitialPhoneVerificationConfirmView.as_view()),
    path("staff/verification-contact/", VerificationContactUpdateView.as_view()),
    path("staff/email/change/request/", EmailChangeRequestView.as_view()),
    path("staff/email/change/confirm/", EmailChangeConfirmView.as_view()),
    path("staff/phone/change/request/", PhoneChangeRequestView.as_view()),
    path("staff/phone/change/confirm/", PhoneChangeConfirmView.as_view()),
    path("staff/password/change/request/", PasswordChangeRequestView.as_view()),
    path("staff/password/change/confirm/", PasswordChangeConfirmView.as_view()),
    path("staff/reauthenticate/password/", ReauthenticatePasswordView.as_view()),
    path("staff/recovery-codes/", RecoveryCodeListView.as_view()),
    path("staff/private-note/", StaffPrivateNoteView.as_view()),
    path("staff/logout/", StaffLogoutView.as_view()),
    path("recovery/request/", RecoveryRequestView.as_view()),
    path("recovery/confirm/", RecoveryConfirmView.as_view()),
    path("recovery/code/confirm/", RecoveryCodeConfirmView.as_view()),
    path("recovery/reset/", RecoveryResetView.as_view()),
    path("passkeys/", PasskeyListView.as_view()),
    path("passkeys/register/options/", PasskeyRegistrationOptionsView.as_view()),
    path("passkeys/register/complete/", PasskeyRegistrationCompleteView.as_view()),
    path("passkeys/auth/options/", PasskeyAuthenticationOptionsView.as_view()),
    path("passkeys/auth/complete/", PasskeyAuthenticationCompleteView.as_view()),
    path("passkeys/reauthenticate/", PasskeyReauthenticationCompleteView.as_view()),
    path("passkeys/<uuid:passkey_id>/", PasskeyDeleteView.as_view()),
    path("devices/", TrustedDeviceListView.as_view()),
    path("devices/<uuid:device_id>/", TrustedDeviceDeleteView.as_view()),
    path("devices/pairing/", DevicePairingStartView.as_view()),
    path("devices/pairing/status/", DevicePairingStatusView.as_view()),
    path("devices/pairing/approve/", DevicePairingApproveView.as_view()),
    path("devices/contact/request/", DeviceContactAuthorizationRequestView.as_view()),
    path("devices/contact/confirm/", DeviceContactAuthorizationConfirmView.as_view()),
    path("clinic/assistant/", ClinicAssistantView.as_view()),
    path("clinic/assistant/setup/", AssistantSetupView.as_view()),
    path("clinic/assistant/setup/info/", AssistantSetupInfoView.as_view()),
    path("clinic/assistant/setup/claim/", AssistantSetupClaimView.as_view()),
    path("clinic/assistant/recovery/", AssistantRecoveryInitiateView.as_view()),
]
