import { useEffect, useMemo, useState } from "react";

import AccountSettings from "./AccountSettings.jsx";
import { ACTIVE_DEVICE_TOKEN_KEY, ApiError, DEMO_MODE, apiRequest } from "./api.js";
import DemoApp from "./DemoApp.jsx";
import PatientWorkspace from "./PatientWorkspace.jsx";
import { getPasskey } from "./webauthn.js";
import { Brand, ErrorMessage, Field } from "./ui.jsx";
import "./deviceAccess.css";
import "./phase8.css";

const STAFF_TOKEN_KEY = "health-hub.staff-token";
const DEVICE_MAP_KEY = "health-hub.device-tokens.v2";

function loadDeviceMap() {
  try {
    const parsed = JSON.parse(localStorage.getItem(DEVICE_MAP_KEY) || "{}");
    return parsed && typeof parsed === "object" ? parsed : {};
  } catch {
    return {};
  }
}
function savedDeviceToken(clinicId) { return loadDeviceMap()[clinicId] ?? null; }
function saveDeviceToken(clinicId, token) {
  const map = loadDeviceMap(); map[clinicId] = token; localStorage.setItem(DEVICE_MAP_KEY, JSON.stringify(map));
}
function removeSavedDeviceToken(clinicId) {
  const map = loadDeviceMap(); delete map[clinicId]; localStorage.setItem(DEVICE_MAP_KEY, JSON.stringify(map));
}
function asError(error, fallback) { return error instanceof ApiError ? error : new ApiError(error?.message || fallback); }

function AuthShell({ title, description, children, onBack, aside }) {
  return <main className="auth-layout"><section className="auth-intro"><Brand/><div><p className="eyebrow">Personal account · clinic-scoped access</p><h1>{title}</h1><p>{description}</p>{aside}</div></section><section className="auth-panel">{onBack&&<button className="back-button" type="button" onClick={onBack}>← Back</button>}{children}</section></main>;
}
function LoadingScreen(){return <div className="loading-screen"><Brand/><div className="loader" aria-label="Loading"/></div>}

function Landing({ onLogin, onNewClinic, onJoin, onRecovery }) {
  return <AuthShell title="Your account first. Your clinic second." description="Health Hub keeps your personal identity, verified contacts, passkeys, and recovery separate from each clinic. Clinic records open only after that clinic trusts this browser."><div className="panel-heading"><p className="eyebrow">Health Hub</p><h2>Continue</h2><p>Existing staff sign in with verified email or phone. New Doctors create a clinic; replacement/new Assistants use the Doctor&apos;s one-time setup code.</p></div><div className="choice-stack"><button className="choice-card" type="button" onClick={onLogin}><span className="choice-card__icon">→</span><span><strong>Sign in</strong><small>Email or phone + password, or a registered passkey.</small></span><span>→</span></button><button className="choice-card" type="button" onClick={onNewClinic}><span className="choice-card__icon">+</span><span><strong>Create clinic</strong><small>Create the clinic and its first Doctor personal account.</small></span><span>→</span></button><button className="choice-card" type="button" onClick={onJoin}><span className="choice-card__icon">↳</span><span><strong>Join as Assistant</strong><small>Use a one-time setup code created by the clinic Doctor.</small></span><span>→</span></button></div><button className="back-button" type="button" onClick={onRecovery}>Forgot password?</button></AuthShell>;
}

function LoginForm({ onSubmit, onPasskey, onBack, onRecovery }) {
  const [form,setForm]=useState({identity:"",password:""}),[error,setError]=useState(null),[busy,setBusy]=useState(false);
  function update(e){setForm((x)=>({...x,[e.target.name]:e.target.value}))}
  async function submit(e){e.preventDefault();setBusy(true);setError(null);try{await onSubmit(form)}catch(x){setError(asError(x,"Sign in failed."))}finally{setBusy(false)}}
  async function passkey(){setBusy(true);setError(null);try{await onPasskey(form.identity)}catch(x){setError(asError(x,"Passkey sign in failed."))}finally{setBusy(false)}}
  return <AuthShell title="Sign in to your personal account." description="Clinic selection and trusted-device authorization happen after personal authentication." onBack={onBack}><form className="form" onSubmit={submit}><ErrorMessage error={error}/><Field label="Email or phone" name="identity" value={form.identity} onChange={update} autoComplete="username" required/><Field label="Password" name="password" type="password" value={form.password} onChange={update} autoComplete="current-password" required/><button className="primary-button" disabled={busy}>{busy?"Please wait…":"Sign in"}</button><button type="button" disabled={busy||!form.identity.trim()} onClick={passkey}>Use passkey instead</button><button className="back-button" type="button" onClick={onRecovery}>Forgot password?</button></form></AuthShell>;
}

function NewClinicForm({ onSubmit, onBack }) {
  const [form,setForm]=useState({clinic_name:"",first_name:"",last_name:"",email:"",phone:"",password:"",password_confirm:""}),[error,setError]=useState(null),[busy,setBusy]=useState(false);
  function update(e){setForm((x)=>({...x,[e.target.name]:e.target.value}))}
  async function submit(e){e.preventDefault();setBusy(true);setError(null);try{await onSubmit(form)}catch(x){setError(asError(x,"Clinic account could not be created."))}finally{setBusy(false)}}
  return <AuthShell title="Create a clinic and its Doctor account." description="This browser becomes the first trusted device for the new clinic. The Doctor then verifies both personal email and phone before clinic records can open." onBack={onBack}><form className="form" onSubmit={submit}><ErrorMessage error={error}/><Field label="Clinic name" name="clinic_name" value={form.clinic_name} onChange={update} required/><div className="field-row"><Field label="First name" name="first_name" value={form.first_name} onChange={update} required/><Field label="Last name" name="last_name" value={form.last_name} onChange={update} required/></div><Field label="Personal email" name="email" type="email" value={form.email} onChange={update} autoComplete="email" required/><Field label="Personal phone" name="phone" value={form.phone} onChange={update} placeholder="+33…" autoComplete="tel" required/><Field label="Password" name="password" type="password" value={form.password} onChange={update} autoComplete="new-password" required/><Field label="Confirm password" name="password_confirm" type="password" value={form.password_confirm} onChange={update} autoComplete="new-password" required/><button className="primary-button" disabled={busy}>{busy?"Creating…":"Create clinic and Doctor account"}</button></form></AuthShell>;
}

function AssistantJoinForm({ onSubmit, onBack, existing = false }) {
  const initial=existing?{setup_code:""}:{setup_code:"",first_name:"",last_name:"",email:"",phone:"",password:"",password_confirm:""};
  const[form,setForm]=useState(initial),[error,setError]=useState(null),[busy,setBusy]=useState(false);function update(e){setForm((x)=>({...x,[e.target.name]:e.target.value}))}async function submit(e){e.preventDefault();setBusy(true);setError(null);try{await onSubmit(form)}catch(x){setError(asError(x,"Assistant setup could not be completed."))}finally{setBusy(false)}}
  return <AuthShell title={existing?"Join another clinic as Assistant.":"Create your Assistant account."} description="The one-time setup code grants only the Assistant membership. Clinic records still require verified contacts and a trusted browser." onBack={onBack}><form className="form" onSubmit={submit}><ErrorMessage error={error}/><Field label="Assistant setup code" name="setup_code" value={form.setup_code} onChange={update} placeholder="ABCDE-12345" required/>{!existing&&<><div className="field-row"><Field label="First name" name="first_name" value={form.first_name} onChange={update} required/><Field label="Last name" name="last_name" value={form.last_name} onChange={update} required/></div><Field label="Personal email" name="email" type="email" value={form.email} onChange={update} required/><Field label="Personal phone" name="phone" value={form.phone} onChange={update} placeholder="+33…" required/><Field label="Password" name="password" type="password" value={form.password} onChange={update} required/><Field label="Confirm password" name="password_confirm" type="password" value={form.password_confirm} onChange={update} required/></>}<button className="primary-button" disabled={busy}>{busy?"Please wait…":existing?"Join clinic":"Create Assistant account"}</button></form></AuthShell>;
}

function VerificationGate({ user, staffToken, onUser, onDone }) {
  const [email,setEmail]=useState({sent:false,code:"",dev:""}),[phone,setPhone]=useState({sent:false,code:"",dev:""}),[phoneValue,setPhoneValue]=useState(user.phone??""),[error,setError]=useState(null),[busy,setBusy]=useState(false);
  useEffect(()=>{if(user.account_ready)onDone()},[user.account_ready,onDone]);
  async function addPhone(){setBusy(true);setError(null);try{const p=await apiRequest("/api/staff/profile/",{method:"PATCH",staffToken,data:{phone:phoneValue}});onUser(p.user)}catch(e){setError(asError(e,"Phone could not be saved."))}finally{setBusy(false)}}
  async function request(kind){setBusy(true);setError(null);try{const p=await apiRequest(`/api/staff/verify/${kind}/request/`,{method:"POST",staffToken});const setter=kind==="email"?setEmail:setPhone;setter((x)=>({...x,sent:true,dev:p.development_code??""}))}catch(e){setError(asError(e,"Verification code could not be sent."))}finally{setBusy(false)}}
  async function confirm(kind,state){setBusy(true);setError(null);try{const p=await apiRequest(`/api/staff/verify/${kind}/confirm/`,{method:"POST",staffToken,data:{code:state.code}});onUser(p.user);(kind==="email"?setEmail:setPhone)({sent:false,code:"",dev:""})}catch(e){setError(asError(e,"Verification code is invalid or expired."))}finally{setBusy(false)}}
  return <AuthShell title="Verify your personal contacts." description="Both email and phone must be verified before Health Hub opens any clinic records."><ErrorMessage error={error}/><div className="phase8-verification-grid"><div className="phase8-contact-card"><div><strong>Email</strong><span>{user.email} · {user.email_verified?"Verified":"Verification required"}</span></div>{!user.email_verified&&(!email.sent?<button type="button" disabled={busy} onClick={()=>request("email")}>Send code</button>:<div className="phase8-inline-actions"><input value={email.code} onChange={(e)=>setEmail({...email,code:e.target.value})} placeholder="6-digit code"/><button type="button" disabled={busy} onClick={()=>confirm("email",email)}>Verify</button></div>)}</div>{email.dev&&<p className="security-note">Development code: {email.dev}</p>}<div className="phase8-contact-card"><div><strong>Phone</strong><span>{user.phone||"No phone yet"} · {user.phone_verified?"Verified":"Verification required"}</span></div>{!user.phone&&<div className="phase8-inline-actions"><input value={phoneValue} onChange={(e)=>setPhoneValue(e.target.value)} placeholder="+33…"/><button type="button" disabled={busy} onClick={addPhone}>Save phone</button></div>}{user.phone&&!user.phone_verified&&(!phone.sent?<button type="button" disabled={busy} onClick={()=>request("phone")}>Send SMS code</button>:<div className="phase8-inline-actions"><input value={phone.code} onChange={(e)=>setPhone({...phone,code:e.target.value})} placeholder="6-digit code"/><button type="button" disabled={busy} onClick={()=>confirm("phone",phone)}>Verify</button></div>)}</div>{phone.dev&&<p className="security-note">Development code: {phone.dev}</p>}</div></AuthShell>;
}

function ClinicPicker({ user, onChoose, onCreate, onJoin, onSettings, onSignOut }) {
  return <AuthShell title="Choose a clinic." description="Your profile and security settings are global. Patients, appointments, queues, tasks, and trusted devices remain isolated by clinic."><div className="panel-heading"><p className="eyebrow">{user.display_name}</p><h2>Your clinic memberships</h2></div><div className="phase8-clinic-list">{user.memberships?.map((m)=><button className="choice-card phase8-clinic-button" key={m.id} type="button" onClick={()=>onChoose(m)}><span className={`role-card__badge role-card__badge--${m.role}`}>{m.role[0].toUpperCase()}</span><span><strong>{m.clinic.name}</strong><small>{m.role==="doctor"?"Doctor · Administrator":"Assistant"}</small></span><span>→</span></button>)}</div><div className="phase8-inline-actions">{user.has_doctor_membership&&<button type="button" onClick={onCreate}>Create another clinic</button>}<button type="button" onClick={onJoin}>Join clinic as Assistant</button><button type="button" onClick={onSettings}>Account settings</button><button type="button" onClick={onSignOut}>Sign out</button></div></AuthShell>;
}

function WorkspaceRole({ membership, onSelect, onBack }) {
  const options=membership.role==="doctor"?[["doctor","Doctor workspace","Clinical queue, Room ready, Patient review, and Doctor tasks."],["assistant","Assistant workspace","Administrator access to Patient and appointment operations."]]:[["assistant","Assistant workspace","Patients, appointments, check-in, queue, handoff, and shared tasks."]];
  return <AuthShell title={membership.clinic.name} description="This clinic trusts the current browser. Choose the workspace for this session." onBack={onBack}><div className="choice-stack">{options.map(([role,title,description])=><button className="role-card" type="button" key={role} onClick={()=>onSelect(role)}><span className={`role-card__badge role-card__badge--${role}`}>{role[0].toUpperCase()}</span><span className="role-card__content"><strong>{title}</strong><span>{description}</span></span><span>→</span></button>)}</div></AuthShell>;
}

function DeviceAuthorization({ membership, staffToken, onAuthorized, onBack }) {
  const[channel,setChannel]=useState("email"),[sent,setSent]=useState(false),[code,setCode]=useState(""),[dev,setDev]=useState(""),[pairing,setPairing]=useState(null),[error,setError]=useState(null),[busy,setBusy]=useState(false);
  useEffect(()=>{if(!pairing?.request_token)return;let dead=false;async function poll(){try{const p=await apiRequest("/api/devices/pairing/status/",{method:"POST",staffToken,data:{request_token:pairing.request_token}});if(!dead&&p.status==="approved")onAuthorized(p.device_token)}catch(e){if(!dead)setError(asError(e,"Pairing status could not be checked."))}}poll();const timer=setInterval(poll,2000);return()=>{dead=true;clearInterval(timer)}},[pairing,staffToken,onAuthorized]);
  async function send(){setBusy(true);setError(null);try{const p=await apiRequest("/api/devices/contact/request/",{method:"POST",staffToken,data:{clinic_id:membership.clinic.id,channel}});setSent(true);setDev(p.development_code??"")}catch(e){setError(asError(e,"Device verification could not be sent."))}finally{setBusy(false)}}
  async function confirm(){setBusy(true);setError(null);try{const p=await apiRequest("/api/devices/contact/confirm/",{method:"POST",staffToken,data:{clinic_id:membership.clinic.id,code}});onAuthorized(p.device_token)}catch(e){setError(asError(e,"Device verification failed."))}finally{setBusy(false)}}
  async function startPairing(){setBusy(true);setError(null);try{const p=await apiRequest("/api/devices/pairing/",{method:"POST",staffToken,data:{clinic_id:membership.clinic.id}});setPairing(p)}catch(e){setError(asError(e,"Pairing could not be started."))}finally{setBusy(false)}}
  return <AuthShell title={`Trust this browser for ${membership.clinic.name}.`} description="Device trust is per clinic. Choose a verified contact channel, or approve a six-digit pairing code from an already trusted device." onBack={onBack}><ErrorMessage error={error}/>{pairing?<><div className="panel-heading"><p className="eyebrow">Pair from another trusted device</p><h2>Approval code</h2><p>Open Devices inside {membership.clinic.name} on a trusted browser and approve this code.</p></div><div className="pairing-code">{pairing.pairing_code.slice(0,3)} {pairing.pairing_code.slice(3)}</div><div className="loader"/></>:<div className="phase8-settings-section"><h3>Authorize with verified contact</h3><select value={channel} onChange={(e)=>{setChannel(e.target.value);setSent(false)}}><option value="email">Verified email</option><option value="sms">Verified SMS</option></select>{!sent?<button className="primary-button" type="button" disabled={busy} onClick={send}>Send verification code</button>:<><Field label="Verification code" value={code} onChange={(e)=>setCode(e.target.value)} required/>{dev&&<p className="security-note">Development code: {dev}</p>}<button className="primary-button" type="button" disabled={busy} onClick={confirm}>Trust this browser</button></>}<hr/><h3>Or pair from a trusted device</h3><button type="button" disabled={busy} onClick={startPairing}>Create pairing code</button></div>}</AuthShell>;
}

function ExistingClinicCreate({ onSubmit, onBack }){const[name,setName]=useState(""),[error,setError]=useState(null),[busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setBusy(true);setError(null);try{await onSubmit(name)}catch(x){setError(asError(x,"Clinic could not be created."))}finally{setBusy(false)}}return <AuthShell title="Create another clinic." description="Your existing personal Doctor account will become the Doctor membership for this new clinic." onBack={onBack}><form className="form" onSubmit={submit}><ErrorMessage error={error}/><Field label="Clinic name" value={name} onChange={(e)=>setName(e.target.value)} required/><button className="primary-button" disabled={busy}>{busy?"Creating…":"Create clinic"}</button></form></AuthShell>}

function RecoveryFlow({ onBack, onComplete }) {
  const[step,setStep]=useState("request"),[identity,setIdentity]=useState(""),[channel,setChannel]=useState("email"),[code,setCode]=useState(""),[recoveryToken,setRecoveryToken]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[error,setError]=useState(null),[busy,setBusy]=useState(false),[offline,setOffline]=useState(false);
  async function request(e){e.preventDefault();setBusy(true);setError(null);try{if(offline){const p=await apiRequest("/api/recovery/code/confirm/",{method:"POST",data:{identity,code}});setRecoveryToken(p.recovery_token);setStep("reset")}else{await apiRequest("/api/recovery/request/",{method:"POST",data:{identity,channel}});setStep("confirm")}}catch(x){setError(asError(x,"Recovery could not be started."))}finally{setBusy(false)}}
  async function verify(e){e.preventDefault();setBusy(true);setError(null);try{const p=await apiRequest("/api/recovery/confirm/",{method:"POST",data:{identity,code}});setRecoveryToken(p.recovery_token);setStep("reset")}catch(x){setError(asError(x,"Recovery code is invalid or expired."))}finally{setBusy(false)}}
  async function reset(e){e.preventDefault();setBusy(true);setError(null);try{await apiRequest("/api/recovery/reset/",{method:"POST",data:{recovery_token:recoveryToken,password,password_confirm:confirm}});onComplete()}catch(x){setError(asError(x,"Password could not be reset."))}finally{setBusy(false)}}
  return <AuthShell title="Recover your personal account." description="Use verified email/SMS. Doctors may alternatively use one unused offline recovery code." onBack={onBack}><ErrorMessage error={error}/>{step==="request"&&<form className="form" onSubmit={request}><Field label="Email or phone" value={identity} onChange={(e)=>setIdentity(e.target.value)} required/><label><input type="checkbox" checked={offline} onChange={(e)=>{setOffline(e.target.checked);setCode("")}}/> Use a Doctor offline recovery code</label>{offline?<Field label="Offline recovery code" value={code} onChange={(e)=>setCode(e.target.value)} required/>:<><label>Recovery channel</label><select value={channel} onChange={(e)=>setChannel(e.target.value)}><option value="email">Email</option><option value="sms">SMS</option></select></>}<button className="primary-button" disabled={busy}>Continue</button></form>}{step==="confirm"&&<form className="form" onSubmit={verify}><p className="security-note">If the account and chosen verified channel exist, a code has been sent.</p><Field label="Recovery code" value={code} onChange={(e)=>setCode(e.target.value)} required/><button className="primary-button" disabled={busy}>Verify code</button></form>}{step==="reset"&&<form className="form" onSubmit={reset}><Field label="New password" type="password" value={password} onChange={(e)=>setPassword(e.target.value)} required/><Field label="Confirm new password" type="password" value={confirm} onChange={(e)=>setConfirm(e.target.value)} required/><button className="primary-button" disabled={busy}>Reset password</button></form>}</AuthShell>;
}

function AccountSettingsStandalone({ user, staffToken, onUserChange, onBack }) { return <AuthShell title="Account settings" description="Open settings, then return to clinic selection." onBack={onBack}><div className="panel-heading"><h2>{user.display_name}</h2><p>{user.email} · {user.phone}</p></div><AccountSettings user={user} staffToken={staffToken} onUserChange={onUserChange}/></AuthShell>; }

function ProductionApp(){
  const[screen,setScreen]=useState("loading"),[staffToken,setStaffToken]=useState(null),[user,setUser]=useState(null),[pendingMembership,setPendingMembership]=useState(null),[pendingDeviceToken,setPendingDeviceToken]=useState(null),[newClinicToken,setNewClinicToken]=useState(null);
  const activeMembership=useMemo(()=>user?.clinic?user.memberships?.find((m)=>m.clinic.id===user.clinic.id)??null:null,[user]);
  const routeUser=(next)=>{setUser(next);if(!next.account_ready){setScreen("verify");return}if(next.clinic&&next.workspace_role){setScreen("workspace");return}setScreen("clinics")};
  useEffect(()=>{async function restore(){const token=localStorage.getItem(STAFF_TOKEN_KEY);if(!token){setScreen("landing");return}try{const p=await apiRequest("/api/staff/me/",{staffToken:token});setStaffToken(token);routeUser(p.user)}catch{localStorage.removeItem(STAFF_TOKEN_KEY);localStorage.removeItem(ACTIVE_DEVICE_TOKEN_KEY);setScreen("landing")}}restore()},[]);
  async function login(form){const p=await apiRequest("/api/staff/login/",{method:"POST",data:form});localStorage.setItem(STAFF_TOKEN_KEY,p.session_token);localStorage.removeItem(ACTIVE_DEVICE_TOKEN_KEY);setStaffToken(p.session_token);routeUser(p.user)}
  async function passkeyLogin(identity){const begin=await apiRequest("/api/passkeys/auth/options/",{method:"POST",data:{identity}});const credential=await getPasskey(begin.public_key);const p=await apiRequest("/api/passkeys/auth/complete/",{method:"POST",data:{identity,credential}});localStorage.setItem(STAFF_TOKEN_KEY,p.session_token);localStorage.removeItem(ACTIVE_DEVICE_TOKEN_KEY);setStaffToken(p.session_token);routeUser(p.user)}
  async function createFirstClinic(form){const clinic=await apiRequest("/api/clinics/",{method:"POST",data:{name:form.clinic_name}});saveDeviceToken(clinic.clinic.id,clinic.device_token);localStorage.setItem(ACTIVE_DEVICE_TOKEN_KEY,clinic.device_token);setNewClinicToken(clinic.device_token);const p=await apiRequest("/api/staff/register/",{method:"POST",deviceToken:clinic.device_token,data:{role:"doctor",first_name:form.first_name,last_name:form.last_name,email:form.email,phone:form.phone,password:form.password,password_confirm:form.password_confirm}});localStorage.setItem(STAFF_TOKEN_KEY,p.session_token);setStaffToken(p.session_token);routeUser(p.user)}
  async function createAssistant(form){const p=await apiRequest("/api/staff/register/",{method:"POST",data:{role:"assistant",...form}});localStorage.setItem(STAFF_TOKEN_KEY,p.session_token);localStorage.removeItem(ACTIVE_DEVICE_TOKEN_KEY);setStaffToken(p.session_token);routeUser(p.user)}
  async function chooseMembership(membership){setPendingMembership(membership);const token=savedDeviceToken(membership.clinic.id);if(token){try{await apiRequest("/api/clinic/context/",{deviceToken:token});setPendingDeviceToken(token);setScreen("workspace-role");return}catch{removeSavedDeviceToken(membership.clinic.id)}}setPendingDeviceToken(null);setScreen("device-auth")}
  function deviceAuthorized(token){saveDeviceToken(pendingMembership.clinic.id,token);setPendingDeviceToken(token);setScreen("workspace-role")}
  async function openWorkspace(role){const p=await apiRequest("/api/staff/select-clinic/",{method:"POST",staffToken,deviceToken:pendingDeviceToken,data:{clinic_id:pendingMembership.clinic.id,workspace_role:role}});localStorage.setItem(ACTIVE_DEVICE_TOKEN_KEY,pendingDeviceToken);setUser(p.user);setScreen("workspace")}
  async function switchClinic(){try{const p=await apiRequest("/api/staff/leave-clinic/",{method:"POST",staffToken});localStorage.removeItem(ACTIVE_DEVICE_TOKEN_KEY);setUser(p.user);setPendingMembership(null);setPendingDeviceToken(null);setScreen("clinics")}catch{await signOut()}}
  async function signOut(){try{if(staffToken)await apiRequest("/api/staff/logout/",{method:"POST",staffToken})}catch{}localStorage.removeItem(STAFF_TOKEN_KEY);localStorage.removeItem(ACTIVE_DEVICE_TOKEN_KEY);setStaffToken(null);setUser(null);setPendingMembership(null);setPendingDeviceToken(null);setScreen("landing")}
  function currentDeviceRemoved(){if(user?.clinic)removeSavedDeviceToken(user.clinic.id);localStorage.removeItem(STAFF_TOKEN_KEY);localStorage.removeItem(ACTIVE_DEVICE_TOKEN_KEY);setStaffToken(null);setUser(null);setScreen("landing")}
  async function createAdditionalClinic(name){const created=await apiRequest("/api/clinics/",{method:"POST",data:{name}});saveDeviceToken(created.clinic.id,created.device_token);await apiRequest(`/api/clinics/${created.clinic.id}/claim-doctor/`,{method:"POST",staffToken,deviceToken:created.device_token});const refreshed=await apiRequest("/api/staff/me/",{staffToken});setUser(refreshed.user);const membership=refreshed.user.memberships.find((m)=>m.clinic.id===created.clinic.id);setPendingMembership(membership);setPendingDeviceToken(created.device_token);setScreen("workspace-role")}
  async function joinExistingClinic(form){const token=savedDeviceToken(pendingMembership?.clinic?.id);const p=await apiRequest("/api/clinic/assistant/setup/claim/",{method:"POST",staffToken,deviceToken:token||undefined,data:{code:form.setup_code,workspace_role:"assistant"}});setUser(p.user);setScreen("clinics")}
  if(screen==="loading")return <LoadingScreen/>;
  if(screen==="landing")return <Landing onLogin={()=>setScreen("login")} onNewClinic={()=>setScreen("new-clinic")} onJoin={()=>setScreen("new-assistant")} onRecovery={()=>setScreen("recovery")}/>;
  if(screen==="login")return <LoginForm onSubmit={login} onPasskey={passkeyLogin} onBack={()=>setScreen("landing")} onRecovery={()=>setScreen("recovery")}/>;
  if(screen==="new-clinic")return <NewClinicForm onSubmit={createFirstClinic} onBack={()=>setScreen("landing")}/>;
  if(screen==="new-assistant")return <AssistantJoinForm onSubmit={createAssistant} onBack={()=>setScreen("landing")}/>;
  if(screen==="recovery")return <RecoveryFlow onBack={()=>setScreen("landing")} onComplete={()=>setScreen("login")}/>;
  if(screen==="verify"&&user&&staffToken)return <VerificationGate user={user} staffToken={staffToken} onUser={setUser} onDone={()=>{if(user.clinic){const membership=user.memberships.find((m)=>m.clinic.id===user.clinic.id);setPendingMembership(membership);const token=savedDeviceToken(user.clinic.id)||newClinicToken;setPendingDeviceToken(token);setScreen("workspace-role")}else setScreen("clinics")}}/>;
  if(screen==="clinics"&&user&&staffToken)return <ClinicPicker user={user} onChoose={chooseMembership} onCreate={()=>setScreen("create-more-clinic")} onJoin={()=>setScreen("join-existing")} onSettings={()=>setScreen("account-settings")} onSignOut={signOut}/>;
  if(screen==="create-more-clinic")return <ExistingClinicCreate onSubmit={createAdditionalClinic} onBack={()=>setScreen("clinics")}/>;
  if(screen==="join-existing")return <AssistantJoinForm existing onSubmit={joinExistingClinic} onBack={()=>setScreen("clinics")}/>;
  if(screen==="account-settings"&&user)return <AccountSettingsStandalone user={user} staffToken={staffToken} onUserChange={setUser} onBack={()=>setScreen("clinics")}/>;
  if(screen==="device-auth"&&pendingMembership)return <DeviceAuthorization membership={pendingMembership} staffToken={staffToken} onAuthorized={deviceAuthorized} onBack={()=>setScreen("clinics")}/>;
  if(screen==="workspace-role"&&pendingMembership&&pendingDeviceToken)return <WorkspaceRole membership={pendingMembership} onSelect={openWorkspace} onBack={()=>setScreen("clinics")}/>;
  if(screen==="workspace"&&user&&staffToken)return <PatientWorkspace user={user} staffToken={staffToken} onSignOut={signOut} onCurrentDeviceRemoved={currentDeviceRemoved} onSwitchClinic={switchClinic} onUserChange={setUser}/>;
  return <LoadingScreen/>;
}

export default function App(){return DEMO_MODE?<DemoApp/>:<ProductionApp/>}
