import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { ApiError, DEMO_MODE, apiRequest } from "./api.js";
import { ErrorMessage } from "./ui.jsx";
import "./deviceAccess.css";

function formatAdded(value){return value?new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",year:"numeric"}).format(new Date(value)):"Unknown date"}
function DeviceModal({staffToken,onClose,onCurrentDeviceRemoved}){const[devices,setDevices]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(null),[pairingCode,setPairingCode]=useState(""),[approving,setApproving]=useState(false),[approved,setApproved]=useState(null),[removing,setRemoving]=useState(null);async function load(){setLoading(true);try{const p=await apiRequest("/api/devices/",{staffToken});setDevices(p.devices??[])}catch(e){setError(e instanceof ApiError?e:new ApiError("Trusted devices could not be loaded."))}finally{setLoading(false)}}useEffect(()=>{load()},[]);async function approve(e){e.preventDefault();setApproving(true);setError(null);try{const p=await apiRequest("/api/devices/pairing/approve/",{method:"POST",staffToken,data:{code:pairingCode}});setApproved(`${p.browser} on ${p.operating_system}`);setPairingCode("")}catch(x){setError(x instanceof ApiError?x:new ApiError("The device could not be approved."))}finally{setApproving(false)}}async function remove(device){setRemoving(device.id);try{await apiRequest(`/api/devices/${device.id}/`,{method:"DELETE",staffToken});if(device.current){onCurrentDeviceRemoved?.();return}setDevices((d)=>d.filter((x)=>x.id!==device.id))}catch(x){setError(x instanceof ApiError?x:new ApiError("The device could not be removed."))}finally{setRemoving(null)}}return createPortal(<div className="device-modal-backdrop" onMouseDown={(e)=>{if(e.target===e.currentTarget)onClose()}}><section className="device-modal" role="dialog" aria-modal="true"><div className="device-modal__header"><div><p className="eyebrow">Current clinic</p><h2>Trusted devices</h2><p>Trust is specific to this clinic. In Phase 8 you may remove the last device because verified email/SMS can authorize a replacement.</p></div><button className="device-icon-button" onClick={onClose}>×</button></div><ErrorMessage error={error}/><div className="device-list">{loading&&<p>Loading…</p>}{devices.map((d)=><div className="device-row" key={d.id}><div><strong>{d.browser} on {d.operating_system}</strong><span>Added {formatAdded(d.created_at)}{d.current?" · Current device":""}</span></div><button className="device-remove-button" disabled={removing===d.id} onClick={()=>remove(d)}>{removing===d.id?"Removing…":"Remove"}</button></div>)}</div><div className="device-pair-panel"><div><p className="eyebrow">Approve another browser</p><h3>Pairing code</h3><p>The new browser can alternatively authorize itself using this account&apos;s verified email or SMS.</p></div>{approved&&<p className="device-success">{approved} approved.</p>}<form className="device-pair-form" onSubmit={approve}><label>Pairing code</label><div><input value={pairingCode} onChange={(e)=>setPairingCode(e.target.value)} placeholder="123 456" maxLength={7} required/><button className="primary-button" disabled={approving}>{approving?"Approving…":"Approve device"}</button></div></form></div></section></div>,document.body)}
export default function TrustedDevices({staffToken,onCurrentDeviceRemoved}){const[open,setOpen]=useState(false);if(DEMO_MODE)return null;return <><button type="button" onClick={()=>setOpen(true)}>Devices</button>{open&&<DeviceModal staffToken={staffToken} onClose={()=>setOpen(false)} onCurrentDeviceRemoved={onCurrentDeviceRemoved}/>}</>}
